# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 05:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20161228_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.Collection'),
        ),
    ]
