# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20170106_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='last_take',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='place_in_collection',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
